/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_progra;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;




/**
 *
 * @author elder
 */
public class Nuevo_ingresoPanel extends javax.swing.JPanel {

    /**
     * Creates new form Nuevo_ingresoPanel
     */
    public Nuevo_ingresoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_carne = new javax.swing.JLabel();
        txt_carne = new javax.swing.JTextField();
        lbl_numPlaca = new javax.swing.JLabel();
        txt_numPlaca = new javax.swing.JTextField();
        cbxTipodeVehiculo = new javax.swing.JComboBox<>();
        lblTipodeVehiculo = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        cbxArea = new javax.swing.JComboBox<>();
        btnGusuario = new javax.swing.JButton();
        lblTipodeTarifa = new javax.swing.JLabel();
        cbxTarifa = new javax.swing.JComboBox<>();

        lbl_carne.setText("Ingresa tu numero de Carné");

        txt_carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_carneActionPerformed(evt);
            }
        });

        lbl_numPlaca.setText("ingresa Tu numero de Placa");

        cbxTipodeVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));

        lblTipodeVehiculo.setText("Selecciona tu Tipo de Vehiculo:");

        lblArea.setText("Selecciona tu Área:");

        cbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Catedrático", "Visita" }));

        btnGusuario.setText("Guardar Usuario");
        btnGusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGusuarioActionPerformed(evt);
            }
        });

        lblTipodeTarifa.setText("Ingrese Tipo de Tarifa:");

        cbxTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarifa Plana (Q10 todo el día)", "Tarifa Variable (por hora)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_numPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_numPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txt_carne, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxTipodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTipodeVehiculo)
                                .addComponent(lblArea)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cbxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblTipodeTarifa))
                            .addComponent(cbxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_carne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_numPlaca)
                .addGap(18, 18, 18)
                .addComponent(txt_numPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTipodeVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipodeTarifa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnGusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_carneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_carneActionPerformed

    private void btnGusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGusuarioActionPerformed
// Extraigo valores de los TextField
    String carne = txt_carne.getText().trim();
    String placa = txt_numPlaca.getText().trim();
    String tipoVehiculo = (String) cbxTipodeVehiculo.getSelectedItem();

    // Verifico si los campos no están vacíos
    if (carne.isEmpty() || placa.isEmpty() || tipoVehiculo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Por favor, complete todos los campos antes de guardar.",
            "Campos vacíos",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = ConexionBD.conectar()) {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Error: no se pudo conectar a la base de datos.");
            return;
        }

        // Inserto el vehículo (solo si no existe)
        String sql = "INSERT INTO vehiculo (carne, placa, Tipo_vehiculo) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, carne);
        ps.setString(2, placa);
        ps.setString(3, tipoVehiculo);

        int filas = ps.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Vehículo ingresado correctamente.");

            

            // Obtengo la tarifa seleccionada del ComboBox
            String tarifaSeleccionada = cbxTarifa.getSelectedItem().toString();
           
            
            
            

            // Defino variables base para el ticket
            String modoPago;
            double monto;
            String estado;

            // detecto tarifa plana
            if (tarifaSeleccionada.startsWith("Tarifa Plana")) {

                
                modoPago = "FLAT";
                monto = 10.00;
                estado = "PAGADO";
            } else {
                // Si eligió tarifa variable, se paga al salir
                modoPago = "VARIABLE";
                monto = 0.00;
                estado = "ACTIVO";
            }
            
            
            
            

            // Inserto el nuevo ticket en la base de datos
            String sqlTicket = "INSERT INTO ticket (placa, fecha_ingreso, modo_pago, monto, estado) VALUES (?, NOW(), ?, ?, ?)";
            PreparedStatement psTicket = conn.prepareStatement(sqlTicket);
            psTicket.setString(1, placa);
            psTicket.setString(2, modoPago);
            psTicket.setDouble(3, monto);
            psTicket.setString(4, estado);

            int filasTicket = psTicket.executeUpdate();

            // Si se insertó el ticket correctamente
            if (filasTicket > 0) {
                // Hora actual formateada
                String horaEntrada = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                
                
                

                
                
                
                
                
                
                
                
                
                

                // Creo el texto del ticket
                String ticket = "------ PARQUEO UMG ------\n"
                        + "Placa: " + placa + "\n"
                        + "Tipo de vehículo: " + cbxTipodeVehiculo.getSelectedItem() + "\n"
                        + "Tipo de Tarifa: " + tarifaSeleccionada + "\n"
                        + "Hora de Entrada: " + horaEntrada + "\n"
                        + "--------------------------\n"
                        + "BIENVENIDO!\n";

                // Muestro el ticket en una ventana
                JOptionPane.showMessageDialog(this, ticket, "Ticket de entrada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo generar el ticket.");
            }

            // 🔼 🔼 🔼 FIN DEL BLOQUE PARA CREAR EL TICKET 🔼 🔼 🔼

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el vehículo.");
        }
// limpio
            txt_carne.setText("");
            txt_numPlaca.setText("");
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
}

 
    }//GEN-LAST:event_btnGusuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGusuario;
    private javax.swing.JComboBox<String> cbxArea;
    private javax.swing.JComboBox<String> cbxTarifa;
    private javax.swing.JComboBox<String> cbxTipodeVehiculo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblTipodeTarifa;
    private javax.swing.JLabel lblTipodeVehiculo;
    private javax.swing.JLabel lbl_carne;
    private javax.swing.JLabel lbl_numPlaca;
    private javax.swing.JTextField txt_carne;
    private javax.swing.JTextField txt_numPlaca;
    // End of variables declaration//GEN-END:variables
}
