/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_progra;

import com.mycompany.proyecto_progra.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_progra.Ticket;
import com.mycompany.proyecto_progra.TicketDAO;





/**
 *
 * @author elder
 */
public class Nuevo_ingresoPanel extends javax.swing.JPanel {

    /**
     * Creates new form Nuevo_ingresoPanel
     */
    public Nuevo_ingresoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_carne = new javax.swing.JLabel();
        txt_carne = new javax.swing.JTextField();
        lbl_numPlaca = new javax.swing.JLabel();
        txt_numPlaca = new javax.swing.JTextField();
        cbxTipodeVehiculo = new javax.swing.JComboBox<>();
        lblTipodeVehiculo = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        cbxArea = new javax.swing.JComboBox<>();
        btnGusuario = new javax.swing.JButton();
        lblTipodeTarifa = new javax.swing.JLabel();
        cbxTarifa = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        lbl_carne.setText("Ingresa tu numero de Carné:");

        txt_carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_carneActionPerformed(evt);
            }
        });

        lbl_numPlaca.setText("ingresa Tu numero de Placa:");

        cbxTipodeVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));

        lblTipodeVehiculo.setText("Selecciona tu Tipo de Vehiculo:");

        lblArea.setText("Selecciona tu Área:");

        cbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Catedrático", "Visita" }));

        btnGusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-datos.png"))); // NOI18N
        btnGusuario.setText("Guardar Usuario");
        btnGusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGusuarioActionPerformed(evt);
            }
        });

        lblTipodeTarifa.setText("Ingrese Tipo de Tarifa:");

        cbxTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarifa Plana (Q10 todo el día)", "Tarifa Variable (por hora)" }));
        cbxTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTarifaActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida-de-incendios.png"))); // NOI18N
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbxTipodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipodeVehiculo)
                            .addComponent(lblArea)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTipodeTarifa))
                        .addComponent(cbxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_numPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_numPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_carne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_numPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_numPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipodeVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipodeVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipodeTarifa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_carneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_carneActionPerformed

    private void btnGusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGusuarioActionPerformed

                                               
    // Extraigo valores de los TextField
    String carne = txt_carne.getText().trim();
    String placa = txt_numPlaca.getText().trim();
    String tipoVehiculo = (String) cbxTipodeVehiculo.getSelectedItem();

    // Verifico si los campos no están vacíos
    if (carne.isEmpty() || placa.isEmpty() || tipoVehiculo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Por favor, complete todos los campos antes de guardar.",
            "Campos vacíos",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = ConexionBD.conectar()) {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Error: no se pudo conectar a la base de datos.");
            return;
        }

        // Inserto el vehículo (solo si no existe)
        String sql = "INSERT INTO vehiculo (carne, placa, Tipo_vehiculo) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, carne);
        ps.setString(2, placa);
        ps.setString(3, tipoVehiculo);

        int filas = ps.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Vehículo ingresado correctamente.");

            // CLASE DAO 

            // Obtengo la tarifa seleccionada del Cbx
            String tarifaSeleccionada = cbxTarifa.getSelectedItem().toString();

            // Creo el objeto Ticket con sus valores
            Ticket nuevoTicket = new Ticket();
            nuevoTicket.setPlaca(placa);
            nuevoTicket.setArea_id(null); 
            nuevoTicket.setFecha_ingreso(new java.sql.Timestamp(System.currentTimeMillis()));

            // Detecto tipo de tarifa
            if (tarifaSeleccionada.startsWith("Tarifa Plana")) {
                nuevoTicket.setModo_pago("FLAT");
                nuevoTicket.setMonto(10.00);
                nuevoTicket.setEstado("PAGADO");
            } else {
                nuevoTicket.setModo_pago("VARIABLE");
                nuevoTicket.setMonto(0.00);
                nuevoTicket.setEstado("ACTIVO");
            }


            // Llamo al DAO para guardar el ticket
            TicketDAO.insertarTicket(nuevoTicket);

            // FIN  DAO 


            // Genero el ticket visual
            String horaEntrada = java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

            String ticketTexto = "------ PARQUEO UMG ------\n"
                    + "Placa: " + placa + "\n"
                    + "Tipo de vehículo: " + tipoVehiculo + "\n"
                    + "Tipo de Tarifa: " + tarifaSeleccionada + "\n"
                    + "Hora de Entrada: " + horaEntrada + "\n"
                    + "--------------------------\n"
                    + "BIENVENIDO!\n";

            JOptionPane.showMessageDialog(this, ticketTexto, "Ticket de entrada", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el vehículo.");
        }

        // Limpio campos
        txt_carne.setText("");
        txt_numPlaca.setText("");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
    }

        
            
             

 
    }//GEN-LAST:event_btnGusuarioActionPerformed

    private void cbxTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTarifaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Obtener la ventana principal JFrame
        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (ventana instanceof javax.swing.JFrame frame) {
            //Crear una nueva instancia del panel principal
            parqueoUMG panelPrincipal = new parqueoUMG();

            //Reemplazo el contenido del frame actual por el panel principal
            frame.setContentPane(panelPrincipal.getContentPane());
            frame.revalidate();
            frame.repaint();
        }

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGusuario;
    private javax.swing.JComboBox<String> cbxArea;
    private javax.swing.JComboBox<String> cbxTarifa;
    private javax.swing.JComboBox<String> cbxTipodeVehiculo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblTipodeTarifa;
    private javax.swing.JLabel lblTipodeVehiculo;
    private javax.swing.JLabel lbl_carne;
    private javax.swing.JLabel lbl_numPlaca;
    private javax.swing.JTextField txt_carne;
    private javax.swing.JTextField txt_numPlaca;
    // End of variables declaration//GEN-END:variables
}
